// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users_update.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = $1,
    hashed_password = $2,
    updated_at = NOW()
WHERE id = $3::uuid
RETURNING id, email
`

type UpdateUserParams struct {
	Email          string
	HashedPassword string
	Column3        uuid.UUID
}

type UpdateUserRow struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Email, arg.HashedPassword, arg.Column3)
	var i UpdateUserRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}
