// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users_upgrade.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const upgradeUserToChirpyRed = `-- name: UpgradeUserToChirpyRed :one
UPDATE users
SET
    is_chirpy_red = true,
    updated_at = NOW()
WHERE id = $1
RETURNING is_chirpy_red, updated_at, id
`

type UpgradeUserToChirpyRedRow struct {
	IsChirpyRed sql.NullBool
	UpdatedAt   time.Time
	ID          uuid.UUID
}

func (q *Queries) UpgradeUserToChirpyRed(ctx context.Context, id uuid.UUID) (UpgradeUserToChirpyRedRow, error) {
	row := q.db.QueryRowContext(ctx, upgradeUserToChirpyRed, id)
	var i UpgradeUserToChirpyRedRow
	err := row.Scan(&i.IsChirpyRed, &i.UpdatedAt, &i.ID)
	return i, err
}
